#To immerse yourself in the world of RewardADs, browse our wiki: https://rewardads.vpsgh.it
code: XXXXXXXXXXX

announce-messages: "&aEarn by clicking:" && "(button) &6Ads now, coins instantly!"
announce-delay: 300
annoucer-enabled: true

earn-per-ad: 100

rewards-commands: "rewards" && "buy" && "givemewhatideserve"