name: RewardADsGui
version: '1.0'
main: it.nathanub.rewardADsGui.Main
api-version: '1.21'
depend:
  - RewardADs
commands:
  buy:
    description: Buy command
    usage: /<buy> or /<rewards>
    aliases: [rewards, reward]