name: RewardADs
version: 1.5
main: it.nathanub.RewardADs.Main
author: ["Nathanub", "Kutateki_"]
api-version: 1.13
softdepend:
  - PlaceholderAPI
commands:
  rewardads:
    description: Spam message and main command
  ad:
    description: Gives ad link